# Generated by Django 4.2.9 on 2024-05-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pin_code',
            field=models.IntegerField(default=12345),
        ),
    ]
