# Generated by Django 4.2.9 on 2024-05-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('orders', '0003_alter_order_address_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='variaton',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variatons',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
