# Generated by Django 4.2.9 on 2024-05-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderproduct_color_remove_orderproduct_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variatons',
            new_name='variations',
        ),
    ]
